Repository YaroslavKSE/BeatRate, pull requests merged in 2025-04, with the labels that each got.

#51 Preview added
  frontend/src/components/Album/AlbumContentTabs.tsx
  frontend/src/components/Album/AlbumHeader.tsx
  frontend/src/components/Album/AlbumTrackList.tsx
  frontend/src/components/Album/AudioVisualizer.tsx
  frontend/src/components/Album/LoadingState.tsx
  frontend/src/components/Song/ErrorState.tsx
  frontend/src/components/Song/LoadingState.tsx
  frontend/src/components/Song/NotFoundState.tsx
  frontend/src/components/Song/SongContentTabs.tsx
  frontend/src/components/Song/SongHeader.tsx
  frontend/src/pages/Album.tsx
  frontend/src/pages/Song.tsx
  frontend/src/store/musicStore.ts
  frontend/src/utils/preview-extractor.ts
  frontend/vite.config.ts
Labels: P1, ABSOLUTE CINEMA✋😐🤚

#52 minor visualizer improvement
  frontend/src/components/Album/AudioVisualizer.tsx
Labels: enhancement

#67 Frontend+interactions v2
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/AlbumsController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/TracksController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Program.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/BatchResponcesDTO.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/IAlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISpotifyApiClient.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ITrackService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Requests/BatchIdsRequest.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/AlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/TrackService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Spotify/SpotifyBatchResponces.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Clients/SpotifyApiClient.cs
  frontend/src/App.tsx
  frontend/src/api/catalog.ts
  frontend/src/api/interaction.ts
  frontend/src/components/Artist/ArtistContentTabs.tsx
  frontend/src/components/Artist/ArtistErrorState.tsx
  frontend/src/components/Artist/ArtistHeader.tsx
  frontend/src/components/Artist/ArtistLoadingState.tsx
  frontend/src/components/Artist/ArtistNotFoundState.tsx
  frontend/src/components/Diary/DiaryDateGroup.tsx
  frontend/src/components/Diary/DiaryEntry.tsx
  frontend/src/components/Diary/DiaryPagination.tsx
  frontend/src/components/Diary/DiaryStates.tsx
  frontend/src/components/Diary/ReviewModal.tsx
  frontend/src/components/Diary/types.ts
  frontend/src/pages/Artist.tsx
  frontend/src/pages/Diary.tsx
  frontend/src/pages/Home.tsx
  frontend/src/utils/formatters.ts
Labels: P0, ABSOLUTE CINEMA✋😐🤚

#73 Frontend v3
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/ArtistsController.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/ArtistAlbumsResultDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/ArtistTopTracksResultDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/IArtistService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISpotifyApiClient.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/ArtistService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Spotify/SpotifyResponses.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Clients/SpotifyApiClient.cs
  frontend/src/api/catalog.ts
  frontend/src/components/Artist/AlbumCard.tsx
  frontend/src/components/Artist/ArtistContentTabs.tsx
  frontend/src/components/Artist/ArtistHeader.tsx
  frontend/src/components/Artist/TabButton.tsx
  frontend/src/components/Artist/TrackRow.tsx
  frontend/src/pages/Artist.tsx
  frontend/src/pages/Diary.tsx
Labels: P1

#75 Complex interactions frontend
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/AlbumsController.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/AlbumTracksResultDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/IAlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISpotifyApiClient.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/AlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Clients/SpotifyApiClient.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/catalog.ts
  frontend/src/api/interaction.ts
  frontend/src/components/Album/AlbumContentTabs.tsx
  frontend/src/components/Album/AlbumTrackList.tsx
  frontend/src/components/Artist/ArtistContentTabs.tsx
  frontend/src/components/CreateGradingMethod/GradeEditor.tsx
  frontend/src/components/CreateGradingMethod/HelpModal.tsx
  frontend/src/components/CreateInteraction/BlockGrader.tsx
  frontend/src/components/CreateInteraction/DynamicGradingCalculator.tsx
  frontend/src/components/CreateInteraction/GradeSlider.tsx
  frontend/src/components/CreateInteraction/GradingSelector.tsx
  frontend/src/components/CreateInteraction/InteractionButtons.tsx
  frontend/src/components/CreateInteraction/InteractionHeader.tsx
  frontend/src/components/CreateInteraction/InteractionItemDetails.tsx
  frontend/src/components/CreateInteraction/InteractionSubmitButton.tsx
  frontend/src/components/CreateInteraction/InteractionSuccessMessage.tsx
  frontend/src/components/CreateInteraction/MusicInteractionModal.tsx
  frontend/src/components/CreateInteraction/NormalizedStarDisplay.tsx
  frontend/src/components/CreateInteraction/ReviewTextArea.tsx
  frontend/src/components/CreateInteraction/StarRating.tsx
  frontend/src/components/Diary/ComplexRatingModal.tsx
  frontend/src/components/Diary/DiaryEntry.tsx
  frontend/src/components/Search/AlbumResults.tsx
  frontend/src/components/Search/ArtistResults.tsx
  frontend/src/components/Search/LoadMoreButton.tsx
  frontend/src/components/Search/SearchBar.tsx
  frontend/src/components/Search/SearchResults.tsx
  frontend/src/components/Search/TabButton.tsx
  frontend/src/components/Search/TrackResults.tsx
  frontend/src/components/Search/types.ts
  frontend/src/pages/Album.tsx
  frontend/src/pages/CreateGradingMethod.tsx
  frontend/src/pages/CreateInteractionPage.tsx
  frontend/src/pages/Search.tsx
  frontend/src/pages/Song.tsx
  frontend/src/utils/GradeColorUtils.tsx
  frontend/src/utils/preview-extractor.ts
  frontend/src/utils/searchService.ts
  frontend/src/utils/validation-utils.ts
Labels: P0

#96 Music Catalog improvements
  backend/MusicCatalogService/.dockerignore
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/BaseApiController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/PreviewController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Program.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/PreviewItemDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Helpers/ImageHelper.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ICatalogRepository.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ILocalSearchRepository.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/IPreviewService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISpotifyTokenService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Mappers/AlbumMapper.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Mappers/ArtistMapper.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Mappers/TrackMapper.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/Album.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/Artist.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/CatalogItemBase.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/ImageInfo.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/SimplifiedArtist.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/Track.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/AlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/ArtistService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/PreviewService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/SearchService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/SpotifyTokenService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/TrackService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Spotify/TokenResult.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Clients/SpotifyApiClient.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Repositories/LocalSearchRepository.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Repositories/MongoCatalogRepository.cs
  backend/MusicCatalogService/MusicCatalogService.Migrations/Dockerfile.migration
  backend/MusicCatalogService/MusicCatalogService.Migrations/Models/MigrationOptions.cs
  backend/MusicCatalogService/MusicCatalogService.Migrations/MusicCatalogService.Migrations.csproj
  backend/MusicCatalogService/MusicCatalogService.Migrations/Program.cs
  backend/MusicCatalogService/MusicCatalogService.Migrations/Services/MongoDbIndexCreationService.cs
  backend/MusicCatalogService/MusicCatalogService.Migrations/Services/MongoDbMigrationService.cs
  backend/MusicCatalogService/MusicCatalogService.sln
Labels: P1, MusicCatalog
