Repository YaroslavKSE/BeatRate, pull requests merged in 2025-03, with the labels that each got.

#23 Implemented /login and /me endpoints
  backend/UserService/src/UserService.API/UserService.API/Controllers/AuthController.cs
  backend/UserService/src/UserService.API/UserService.API/Controllers/UserController.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Requests/LoginRequest.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Responses/LoginResponse.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Responses/UserProfileResponse.cs
  backend/UserService/src/UserService.API/UserService.API/Program.cs
  backend/UserService/src/UserService.Application/UserService.Application/Commands/LoginCommand.cs
  backend/UserService/src/UserService.Application/UserService.Application/DTOs/AuthTokenResponse.cs
  backend/UserService/src/UserService.Application/UserService.Application/DTOs/LoginResponseDto.cs
  backend/UserService/src/UserService.Application/UserService.Application/Handlers/GetUserProfileQueryHandler.cs
  backend/UserService/src/UserService.Application/UserService.Application/Handlers/LoginCommandHandler.cs
  backend/UserService/src/UserService.Application/UserService.Application/Interfaces/IAuth0Service.cs
  backend/UserService/src/UserService.Application/UserService.Application/Queries/GetUserProfileQuery.cs
  backend/UserService/src/UserService.Application/UserService.Application/Validators/LoginCommandValidator.cs
  backend/UserService/src/UserService.Domain/UserService.Domain/Interfaces/IUserRepository.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Errors/Auth0Error.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Exceptions/Auth0Exception.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Requests/Auth0PasswordTokenRequest.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Responses/Auth0TokenResponse.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Repositories/UserRepository.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Services/Auth0Service.cs
Labels: P0, Story

#26 Music interaction service v2
  backend/MusicInteraction/MusicInteraction.Application/GetInteractionsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/GetLikesCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/GetRatingsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/GetReviewsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/Interfaces/IInteractionStorage.cs
  backend/MusicInteraction/MusicInteraction.Application/PostInteractionCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/WriteReviewCommand.cs
  backend/MusicInteraction/MusicInteraction.Domain/Checked.cs
  backend/MusicInteraction/MusicInteraction.Domain/IGradable.cs
  backend/MusicInteraction/MusicInteraction.Domain/Interaction.cs
  backend/MusicInteraction/MusicInteraction.Domain/InteractionsAggregate.cs
  backend/MusicInteraction/MusicInteraction.Domain/Like.cs
  backend/MusicInteraction/MusicInteraction.Domain/Rating.cs
  backend/MusicInteraction/MusicInteraction.Domain/Review.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalDBTemplate.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalStorages/InteractionStorage.cs
  backend/MusicInteraction/MusicInteraction.Presentation/Controllers/InteractionController.cs
  backend/MusicInteraction/MusicInteraction.Presentation/Program.cs
Labels: Story

#30 Grading methods
  backend/MusicInteraction/MusicInteraction.Application/GetInteractionsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/GetRatingsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/GradingMethodsCommands/CreateGradingMethodCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/GradingMethodsCommands/GetGradingMethodsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/InteractionsCommands/GetInteractionsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/InteractionsCommands/GetLikesCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/InteractionsCommands/GetRatingsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/InteractionsCommands/GetReviewsCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/InteractionsCommands/PostInteractionCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/PostInteractionCommand.cs
  backend/MusicInteraction/MusicInteraction.Application/StorageInterfaces/IGradingMethodStorage.cs
  backend/MusicInteraction/MusicInteraction.Application/StorageInterfaces/IInteractionStorage.cs
  backend/MusicInteraction/MusicInteraction.Domain/Grade.cs
  backend/MusicInteraction/MusicInteraction.Domain/GradingClasses/Grade.cs
  backend/MusicInteraction/MusicInteraction.Domain/GradingClasses/GradingBlock.cs
  backend/MusicInteraction/MusicInteraction.Domain/GradingClasses/GradingMethod.cs
  backend/MusicInteraction/MusicInteraction.Domain/GradingClasses/IGradable.cs
  backend/MusicInteraction/MusicInteraction.Domain/MusicInteractions/Interaction.cs
  backend/MusicInteraction/MusicInteraction.Domain/MusicInteractions/InteractionsAggregate.cs
  backend/MusicInteraction/MusicInteraction.Domain/MusicInteractions/Like.cs
  backend/MusicInteraction/MusicInteraction.Domain/MusicInteractions/Rating.cs
  backend/MusicInteraction/MusicInteraction.Domain/MusicInteractions/Review.cs
  backend/MusicInteraction/MusicInteraction.Domain/Others/Action.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/DependencyInjection.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalDBTemplate.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalStorages/GradingMethodStorage.cs
  backend/MusicInteraction/MusicInteraction.Presentation/Controllers/GradingMethodController.cs
  backend/MusicInteraction/MusicInteraction.Presentation/Controllers/InteractionController.cs
Labels: P0, Epic

#32 MusicInteraction Microservice DB
  backend/MusicInteraction/.dockerignore
  backend/MusicInteraction/Dockerfile
  backend/MusicInteraction/MusicInteraction.Application/InteractionsCommands/GetRatingsCommand.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/DependencyInjection.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalDBTemplate.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalStorages/GradingMethodStorage.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/LocalStorages/InteractionStorage.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/Entities.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/GradingMethodMappers.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/GradingMethodRepository.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/MongoDBContext.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/MongoDBDependencyInjection.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/MongoDBRepository.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/MongoDBSerializationConfig.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MongoDB/MongoGradingMethodStorage.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/MusicInteraction.Infrastructure.csproj
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/DBContextFactory.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/InitialPostgreMigration.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/PosgreSQLContext.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/PosgreSQLInteractionStorage.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/PostgreSQLDependencyInjection.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/PostgreSQLEntities.cs
  backend/MusicInteraction/MusicInteraction.Infrastructure/PostgreSQL/PostgreSQLMapper.cs
  backend/MusicInteraction/MusicInteraction.Presentation/Program.cs
  backend/MusicInteraction/MusicInteraction.Presentation/appsettings.json
  backend/MusicInteraction/docker-compose.yml
Labels: ABSOLUTE CINEMA✋😐🤚

#34 Implemented /google-oauth2 and /logout enpoint
  backend/UserService/src/UserService.API/UserService.API/Controllers/AuthController.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Requests/LogoutRequest.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Requests/SocialLoginRequest.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Responses/LoginResponse.cs
  backend/UserService/src/UserService.API/UserService.API/Models/Responses/LogoutResponse.cs
  backend/UserService/src/UserService.API/UserService.API/Program.cs
  backend/UserService/src/UserService.API/UserService.API/UserService.API.csproj
  backend/UserService/src/UserService.API/UserService.API/appsettings.Development.json
  backend/UserService/src/UserService.API/UserService.API/appsettings.json
  backend/UserService/src/UserService.Application/UserService.Application/Commands/LogoutCommand.cs
  backend/UserService/src/UserService.Application/UserService.Application/Commands/SocialLoginCommand.cs
  backend/UserService/src/UserService.Application/UserService.Application/DTOs/AuthTokenResponse.cs
  backend/UserService/src/UserService.Application/UserService.Application/DTOs/UserInfoDto.cs
  backend/UserService/src/UserService.Application/UserService.Application/Handlers/LoginCommandHandler.cs
  backend/UserService/src/UserService.Application/UserService.Application/Handlers/LogoutCommandHandler.cs
  backend/UserService/src/UserService.Application/UserService.Application/Handlers/SocialLoginCommandHandler.cs
  backend/UserService/src/UserService.Application/UserService.Application/Interfaces/IAuth0Service.cs
  backend/UserService/src/UserService.Application/UserService.Application/Validators/LogoutCommandValidator.cs
  backend/UserService/src/UserService.Application/UserService.Application/Validators/SocialLoginCommandValidator.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Configuration/Auth0Settings.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Requests/Auth0PasswordTokenRequest.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Requests/Auth0RevokeTokenRequest.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Models/Auth0/Responses/Auth0UserInfoResponse.cs
  backend/UserService/src/UserService.Infrastructure/UserService.Infrastructure/Services/Auth0Service.cs
  backend/UserService/src/docker-compose.yml
Labels: P0, Story

#25 Music catalog service
  backend/MusicCatalogService/Dockerfile
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/AlbumsController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/BaseApiController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/SearchController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Controllers/TracksController.cs
  backend/MusicCatalogService/MusicCatalogService.API/Models/ErrorResponse.cs
  backend/MusicCatalogService/MusicCatalogService.API/MusicCatalogService.API.csproj
  backend/MusicCatalogService/MusicCatalogService.API/Program.cs
  backend/MusicCatalogService/MusicCatalogService.API/appsettings.Development.json
  backend/MusicCatalogService/MusicCatalogService.API/appsettings.json
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/AlbumDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/ArtistDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/BaseSpotifyItemDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/ImageDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/SearchResultDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/DTOs/TrackDto.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Exceptions/SpotifyException.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/IAlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ICacheService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ICatalogRepository.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISearchService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISpotifyApiClient.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ISpotifyTokenService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Interfaces/ITrackService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/Album.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/Artist.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/CatalogItemBase.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/ImageInfo.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/SimplifiedArtist.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Models/Track.cs
  backend/MusicCatalogService/MusicCatalogService.Core/MusicCatalogService.Core.csproj
  backend/MusicCatalogService/MusicCatalogService.Core/Requests/SaveMusicItemRequest.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Responses/ErrorResponse.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Responses/SuccessResponse.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/AlbumService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/SearchService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/SpotifyTokenService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Services/TrackService.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Spotify/SpotifyResponses.cs
  backend/MusicCatalogService/MusicCatalogService.Core/Spotify/SpotifySettings.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Clients/SpotifyApiClient.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Configuration/MongoDbSettings.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/MusicCatalogService.Infrastructure.csproj
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Repositories/MongoCatalogRepository.cs
  backend/MusicCatalogService/MusicCatalogService.Infrastructure/Services/DistributedCacheService.cs
  backend/MusicCatalogService/MusicCatalogService.Tests/MusicCatalogService.Tests.csproj
  backend/MusicCatalogService/MusicCatalogService.Tests/UnitTest1.cs
  backend/MusicCatalogService/MusicCatalogService.sln
  backend/MusicCatalogService/ReadMe.md
  backend/MusicCatalogService/docker-compose.yml
Labels: P0, Epic
